### ISSUE TITLE
Example using mhal_i2c

### ISSUE THREAD

**Issue by LennardSchmit** [MediaTek-Labs/mt3620_m4_software#1]
I need to acces a sensor with I2C for a project using the mt3620 M4 cores, and thats why i want to use the mhal_i2.h library. In the API reference manual i can find the implementation of os_hal_ic2.c, but i cant get it to work without os_hal_ic2.h, because of some missing defines. Any idea when we can aspect example code for I2C using the M4 Cores using os_hal_i2c.h?

**Comment by LawranceLiu** [comment]
Please refer to https://github.com/MediaTek-Labs/mt3620_m4_software/tree/master/MT3620_M4_Sample_Code/BareMetal/OS_HAL/inc for the os_hal_i2c.h

**Comment by LennardSchmit** [comment]
Thanks for your help!
