### ISSUE TITLE
How to use I2S interface?

### ISSUE THREAD

**Issue by matsujirushi** [MediaTek-Labs/mt3620_m4_software#16]
I changed MHAL_I2S_TYPE_INTERNAL_LOOPBACK_MODE to  MHAL_I2S_TYPE_EXTERNAL_MODE at MT3620_RTApp_FreeRTOS_I2S.

![image](https://user-images.githubusercontent.com/8079404/80787789-7325e100-8bc2-11ea-806e-8621b4740d55.png)

But no signals without MCLK. (TX, FS and SCLK).

![image](https://user-images.githubusercontent.com/8079404/80787816-85a01a80-8bc2-11ea-94f8-d54cd11fe172.png)

**Comment by LawranceLiu** [comment]
You mean there is signal on MCLK, but no signal on TX/FS/SCLK, right?
SCLK/FS should be generated by I2S Master, and TX would be generated by MT3620 according to the SCLK signal.

**Comment by matsujirushi** [comment]
Hi Lawrance-san,
Thanks for your information.
Sorry. I was wrong.
I thought MT3620 supported I2S master.

"Two I2S interfaces supporting slave and TDM slave modes"
[MT3620 Datasheet](https://d86o2zu8ugzlg.cloudfront.net/mediatek-craft/documents/mt3620/MT3620-Datasheet-v1.4.pdf)
[MT3620 M4 API Reference Manual](https://support.mediatek.com/AzureSphere/mt3620/M4_API_Reference_Manual/)
