### ISSUE TITLE
GPIO Interrupts

### ISSUE THREAD

**Issue by LennardSchmit** [MediaTek-Labs/mt3620_m4_software#2]
The Azure Sphere github page suggests the GPIO interrups do not work yet. 
https://github.com/Azure/azure-sphere-samples/issues/98 
So i wonder, is the use of OS_HAL_EINT.h confirmed to work for GPIO interrupts?
I tried to get it to work but without succes so far.

**Comment by LawranceLiu** [comment]
The GPIO interrupt does not work now due to Azure Sphere OS configuration not ready for it.
We are trying to ask help from Microsoft to fix it.

**Comment by LennardSchmit** [comment]
Thanks for your response! I will just use polling for the time being
