### ISSUE TITLE
Headers are not fully C++ compatible

### ISSUE THREAD

**Issue by JakeSays** [MediaTek-Labs/mt3620_m4_software#27]
Some headers have C++ support in them, some have partial c++ support (`mhal_osai.h` being one) and some have no support.

All headers should be wrapped in `extern "C"` guards.

**Comment by LawranceLiu** [comment]
Thanks for the notification.
We will have a full review and update it in the next release.

**Comment by LawranceLiu** [comment]
Header files are updated in [release_200828](https://github.com/MediaTek-Labs/mt3620_m4_software/commit/88b47b1e9cb26307fda02e6643846f0ca60ca591).

**Comment by LawranceLiu** [comment]
Close this issue due to the solution is included in release_200828. Please reopen if any further issues found.
