### ISSUE TITLE
Add azure-rtos/threadx support.

### ISSUE THREAD

**Issue by JakeSays** [MediaTek-Labs/mt3620_m4_software#28]
There is support for freertos all throughout the code. Since the sphere is a Microsoft device it should support their rtos out of the box.

**Comment by LawranceLiu** [comment]
The current supporting plan of MediaTek-Labs GitHub is FreeRTOS and Bare Metal.
You could refer to the following URL for more sample code: 
https://docs.microsoft.com/en-ca/azure-sphere/resources/resource-overview

**Comment by JakeSays** [comment]
Ok no problem. I'll close.
