### ISSUE TITLE
[Question] About CM4F0 and CM4F1

### ISSUE THREAD

**Issue by Visit-Learn** [MediaTek-Labs/mt3620_m4_software#34]
Hi,

we refer mailbox example for using two RT core. And we have some questions as following,
1. How could I assign RT core firmware into specific M4 part
    (such that we only have one RT core firmware but we want to assign it into CM4F1)

2. If only one RT core firmware and this firmware does not use any dedicate peripheral (such as IO0_GPIO86)
    How could we know that firmware is side load into CM4F0 or CM4F1

Thank you so much.

**Comment by kevinwh-chou** [comment]
Hi,

For your questions, please refers to "8. Determine which core your app is running on" section from [Azure Sphere page](https://docs.microsoft.com/zh-tw/azure-sphere/app-development/develop-debug-rt-app).
Basically the RTApp is deployed to the first available real-time core on the device, and it's not able to specify a particular core. Inside the link it shows a way to know which core is currently used.

**Comment by Visit-Learn** [comment]
Hi,

Thank you for your information, got it.
Thanks~
