### ISSUE TITLE
Data Sharing Between Clicks

### ISSUE THREAD

**Issue by nishithvpoojary** [MediaTek-Labs/mt3620_m4_software#37]
I'm using Avnet starter kit rev 2. Is there any code sample to transfer data from Click1 to Click2. I want to transfer the Click1 Rx data to Click2 and send it to PC using FreeRTOS.

**Comment by LawranceLiu** [comment]
You could refer to the AVENT Azure Sphere Starter Kit User Guide: 
![image](https://user-images.githubusercontent.com/139154/108540986-c45ca980-7296-11eb-9df1-f599d91b6f8d.png)
The "Rx" pin of the Click1 & Click2 is the same.
What data would you like to transfer?

**Comment by nishithvpoojary** [comment]
I connected Tx and Rx of Click1 with jumper wire and sent a printf message. Now I want to transfer that Click 1 Rx data to Click 2 so that I can display it in terminal using click 2. How can I do that?

**Comment by LawranceLiu** [comment]
Hi Nishithvpoojary, 
I'm sorry that I don't really catch your point.
The "Click1 Tx/Rx" and "Click2 Tx/Rx" are mapped to the same pins:
    *. Click1_Tx = Click2_Tx
    *. Click1_Rx = Click2_Rx
If you printf to ISU0, the UART Tx single would be detected on both Click1_TX and Click2_Tx.
If you connect Click1_Tx to Click1_Rx, then, it also means Click2_Tx is connected to Click2_Rx.

Could the above answer your question?
Welcome to let me know if anything not clear.

**Comment by nishithvpoojary** [comment]
Thanks for your reply. Just to clarify, I use **Avnet Azure Starter Kit Rev 2**.
Here are the Pin-outs for Click sockets. It is given that **ISU0(Tx-GPIO26 and Rx-GPIO28)** is dedicated to Click1 and **ISU1(Tx-GPIO31 and Rx-GPIO33)** is dedicated to Click 2. 
![image](https://user-images.githubusercontent.com/45986919/108633255-46b4bb80-7499-11eb-91b3-dfc48236b52e.png)
![image](https://user-images.githubusercontent.com/45986919/108633270-5c29e580-7499-11eb-9810-ecf733b8e784.png)

![Screenshot_20210221_080437](https://user-images.githubusercontent.com/45986919/108613846-a10f3700-741b-11eb-8664-7ae0ff8ab4d7.png) 

- Connected loopback Click1 Tx to Rx and send a message.
- Received message is then sent to Click2 Tx to another Terminal (through FTDI).

The received serial data is corrupted. Is there any efficient way to receive data without any loss?
I use RTApp FreeRTOS (Visual Studio).
Thanks in advance.

**Comment by kevinwh-chou** [comment]
Hi,

What's the purpose for loopback between Click1 Tx to Rx, just for testing?
Guess you check whether the data is corrupted or not on the terminal, what about the received data in the loopback in step1?
Check if the result at each step is expected.

**Comment by nishithvpoojary** [comment]
Yes Kevinwh-chou,
Loopback was for testing purpose. I wanted to check the receiving data. I was able to transfer the data from Click1 to Click2 and the data was not corrupted.
Thankyou LawranceLiu for your response.
