### ISSUE TITLE
Intercore Communication API

### ISSUE THREAD

**Issue by matsujirushi** [MediaTek-Labs/mt3620_m4_software#7]
Hi,
I can not find Intercore Communication API in mt3620_m4_software.
Do you have the plan to produce Intercore Communication API?

**Comment by LawranceLiu** [comment]
MediaTek is now working on M4 driver & sample code for A7<--> M4 and M4 <--> M4 intercore communication. It would be released around late February.

**Comment by matsujirushi** [comment]
Cool!
Thanks for information.

**Comment by LawranceLiu** [comment]
The sample driver & sample code is included in release_200320.
