### ISSUE TITLE
How can I install these drivers 

### ISSUE THREAD

**Issue by ganesh-gawande** [MediaTek-Labs/mt3620_m4_software#8]
How can in install these drivers on windows OS? check for driver update is not working, also i tried to remove the drivers and install it again. 

Please find attached image of device manager. 

![image](https://user-images.githubusercontent.com/12989060/72714874-7a862900-3b95-11ea-9a74-08c098f513c4.png)

**Comment by LawranceLiu** [comment]
Please refer to Microsoft Azure Sphere Docs:
https://docs.microsoft.com/en-ca/azure-sphere/install/install-sdk

**Comment by ganesh-gawande** [comment]
Resolved my issue. Thank you very much
